modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${authors}"
description='''${mod_description}'''

[[dependencies.tcpatch]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tcpatch]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tcpatch]]
    modId="gtceu"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.tcpatch]]
    modId="gtmthings"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
